-- Add all 209 voices to rewards system

-- Clear existing voice rewards to avoid duplicates
DELETE FROM reward_types WHERE category = 'voice';

-- Insert all voices with appropriate rarities
INSERT OR IGNORE INTO reward_types (id, name, description, category, rarity, metadata) VALUES
-- Common voices (most standard languages)
('voice_google_af_ZA', 'Google Afrikaans', 'Afrikaans voice', 'voice', 'common', '{"lang":"af-ZA","engine":"google"}'),
('voice_google_ar_XA', 'Google Arabic', 'Arabic voice', 'voice', 'common', '{"lang":"ar-XA","engine":"google"}'),
('voice_google_bg_BG', 'Google Bulgarian', 'Bulgarian voice', 'voice', 'common', '{"lang":"bg-BG","engine":"google"}'),
('voice_google_bn_IN', 'Google Bengali', 'Bengali voice', 'voice', 'common', '{"lang":"bn-IN","engine":"google"}'),
('voice_google_ca_ES', 'Google Catalan', 'Catalan voice', 'voice', 'common', '{"lang":"ca-ES","engine":"google"}'),
('voice_google_cmn_CN', 'Google Mandarin', 'Mandarin Chinese voice', 'voice', 'common', '{"lang":"cmn-CN","engine":"google"}'),
('voice_google_cmn_TW', 'Google Mandarin Taiwan', 'Taiwanese Mandarin voice', 'voice', 'common', '{"lang":"cmn-TW","engine":"google"}'),
('voice_google_cs_CZ', 'Google Czech', 'Czech voice', 'voice', 'common', '{"lang":"cs-CZ","engine":"google"}'),
('voice_google_da_DK', 'Google Danish', 'Danish voice', 'voice', 'common', '{"lang":"da-DK","engine":"google"}'),
('voice_google_de_DE', 'Google German', 'German voice', 'voice', 'common', '{"lang":"de-DE","engine":"google"}'),
('voice_google_el_GR', 'Google Greek', 'Greek voice', 'voice', 'common', '{"lang":"el-GR","engine":"google"}'),
('voice_google_en_AU', 'Google Australian', 'Australian English voice', 'voice', 'common', '{"lang":"en-AU","engine":"google"}'),
('voice_google_en_GB', 'Google British', 'British English voice', 'voice', 'common', '{"lang":"en-GB","engine":"google"}'),
('voice_google_en_IN', 'Google Indian', 'Indian English voice', 'voice', 'common', '{"lang":"en-IN","engine":"google"}'),
('voice_google_en_US', 'Google American', 'American English voice', 'voice', 'common', '{"lang":"en-US","engine":"google"}'),
('voice_google_es_ES', 'Google Spanish', 'Spanish voice', 'voice', 'common', '{"lang":"es-ES","engine":"google"}'),
('voice_google_es_MX', 'Google Mexican', 'Mexican Spanish voice', 'voice', 'common', '{"lang":"es-MX","engine":"google"}'),
('voice_google_es_US', 'Google US Spanish', 'US Spanish voice', 'voice', 'common', '{"lang":"es-US","engine":"google"}'),
('voice_google_eu_ES', 'Google Basque', 'Basque voice', 'voice', 'uncommon', '{"lang":"eu-ES","engine":"google"}'),
('voice_google_fi_FI', 'Google Finnish', 'Finnish voice', 'voice', 'common', '{"lang":"fi-FI","engine":"google"}'),
('voice_google_fil_PH', 'Google Filipino', 'Filipino voice', 'voice', 'common', '{"lang":"fil-PH","engine":"google"}'),
('voice_google_fr_CA', 'Google Canadian French', 'Canadian French voice', 'voice', 'common', '{"lang":"fr-CA","engine":"google"}'),
('voice_google_fr_FR', 'Google French', 'French voice', 'voice', 'common', '{"lang":"fr-FR","engine":"google"}'),
('voice_google_gl_ES', 'Google Galician', 'Galician voice', 'voice', 'uncommon', '{"lang":"gl-ES","engine":"google"}'),
('voice_google_gu_IN', 'Google Gujarati', 'Gujarati voice', 'voice', 'uncommon', '{"lang":"gu-IN","engine":"google"}'),
('voice_google_he_IL', 'Google Hebrew', 'Hebrew voice', 'voice', 'common', '{"lang":"he-IL","engine":"google"}'),
('voice_google_hi_IN', 'Google Hindi', 'Hindi voice', 'voice', 'common', '{"lang":"hi-IN","engine":"google"}'),
('voice_google_hu_HU', 'Google Hungarian', 'Hungarian voice', 'voice', 'common', '{"lang":"hu-HU","engine":"google"}'),
('voice_google_id_ID', 'Google Indonesian', 'Indonesian voice', 'voice', 'common', '{"lang":"id-ID","engine":"google"}'),
('voice_google_is_IS', 'Google Icelandic', 'Icelandic voice', 'voice', 'uncommon', '{"lang":"is-IS","engine":"google"}'),
('voice_google_it_IT', 'Google Italian', 'Italian voice', 'voice', 'common', '{"lang":"it-IT","engine":"google"}'),
('voice_google_ja_JP', 'Google Japanese', 'Japanese voice', 'voice', 'common', '{"lang":"ja-JP","engine":"google"}'),
('voice_google_kn_IN', 'Google Kannada', 'Kannada voice', 'voice', 'uncommon', '{"lang":"kn-IN","engine":"google"}'),
('voice_google_ko_KR', 'Google Korean', 'Korean voice', 'voice', 'common', '{"lang":"ko-KR","engine":"google"}'),
('voice_google_lt_LT', 'Google Lithuanian', 'Lithuanian voice', 'voice', 'uncommon', '{"lang":"lt-LT","engine":"google"}'),
('voice_google_lv_LV', 'Google Latvian', 'Latvian voice', 'voice', 'uncommon', '{"lang":"lv-LV","engine":"google"}'),
('voice_google_ml_IN', 'Google Malayalam', 'Malayalam voice', 'voice', 'uncommon', '{"lang":"ml-IN","engine":"google"}'),
('voice_google_mr_IN', 'Google Marathi', 'Marathi voice', 'voice', 'uncommon', '{"lang":"mr-IN","engine":"google"}'),
('voice_google_ms_MY', 'Google Malay', 'Malay voice', 'voice', 'uncommon', '{"lang":"ms-MY","engine":"google"}'),
('voice_google_nb_NO', 'Google Norwegian', 'Norwegian voice', 'voice', 'common', '{"lang":"nb-NO","engine":"google"}'),
('voice_google_nl_BE', 'Google Belgian Dutch', 'Belgian Dutch voice', 'voice', 'uncommon', '{"lang":"nl-BE","engine":"google"}'),
('voice_google_nl_NL', 'Google Dutch', 'Dutch voice', 'voice', 'common', '{"lang":"nl-NL","engine":"google"}'),
('voice_google_pa_IN', 'Google Punjabi', 'Punjabi voice', 'voice', 'uncommon', '{"lang":"pa-IN","engine":"google"}'),
('voice_google_pl_PL', 'Google Polish', 'Polish voice', 'voice', 'common', '{"lang":"pl-PL","engine":"google"}'),
('voice_google_pt_BR', 'Google Brazilian', 'Brazilian Portuguese voice', 'voice', 'common', '{"lang":"pt-BR","engine":"google"}'),
('voice_google_pt_PT', 'Google Portuguese', 'Portuguese voice', 'voice', 'common', '{"lang":"pt-PT","engine":"google"}'),
('voice_google_ro_RO', 'Google Romanian', 'Romanian voice', 'voice', 'uncommon', '{"lang":"ro-RO","engine":"google"}'),
('voice_google_ru_RU', 'Google Russian', 'Russian voice', 'voice', 'common', '{"lang":"ru-RU","engine":"google"}'),
('voice_google_sk_SK', 'Google Slovak', 'Slovak voice', 'voice', 'uncommon', '{"lang":"sk-SK","engine":"google"}'),
('voice_google_sr_RS', 'Google Serbian', 'Serbian voice', 'voice', 'uncommon', '{"lang":"sr-RS","engine":"google"}'),
('voice_google_sv_SE', 'Google Swedish', 'Swedish voice', 'voice', 'common', '{"lang":"sv-SE","engine":"google"}'),
('voice_google_ta_IN', 'Google Tamil', 'Tamil voice', 'voice', 'uncommon', '{"lang":"ta-IN","engine":"google"}'),
('voice_google_te_IN', 'Google Telugu', 'Telugu voice', 'voice', 'uncommon', '{"lang":"te-IN","engine":"google"}'),
('voice_google_th_TH', 'Google Thai', 'Thai voice', 'voice', 'common', '{"lang":"th-TH","engine":"google"}'),
('voice_google_tr_TR', 'Google Turkish', 'Turkish voice', 'voice', 'common', '{"lang":"tr-TR","engine":"google"}'),
('voice_google_uk_UA', 'Google Ukrainian', 'Ukrainian voice', 'voice', 'common', '{"lang":"uk-UA","engine":"google"}'),
('voice_google_vi_VN', 'Google Vietnamese', 'Vietnamese voice', 'voice', 'common', '{"lang":"vi-VN","engine":"google"}'),
('voice_google_yue_HK', 'Google Cantonese', 'Cantonese voice', 'voice', 'uncommon', '{"lang":"yue-HK","engine":"google"}'),

-- Specific regional variants (Rare)
('voice_google_en_CA', 'Google Canadian', 'Canadian English voice', 'voice', 'rare', '{"lang":"en-CA","engine":"google"}'),
('voice_google_en_IE', 'Google Irish', 'Irish English voice', 'voice', 'rare', '{"lang":"en-IE","engine":"google"}'),
('voice_google_en_NZ', 'Google New Zealand', 'New Zealand English voice', 'voice', 'rare', '{"lang":"en-NZ","engine":"google"}'),
('voice_google_en_ZA', 'Google South African', 'South African English voice', 'voice', 'rare', '{"lang":"en-ZA","engine":"google"}'),
('voice_google_es_AR', 'Google Argentinian', 'Argentinian Spanish voice', 'voice', 'rare', '{"lang":"es-AR","engine":"google"}'),
('voice_google_es_CL', 'Google Chilean', 'Chilean Spanish voice', 'voice', 'rare', '{"lang":"es-CL","engine":"google"}'),
('voice_google_es_CO', 'Google Colombian', 'Colombian Spanish voice', 'voice', 'rare', '{"lang":"es-CO","engine":"google"}'),
('voice_google_es_PE', 'Google Peruvian', 'Peruvian Spanish voice', 'voice', 'rare', '{"lang":"es-PE","engine":"google"}'),
('voice_google_es_VE', 'Google Venezuelan', 'Venezuelan Spanish voice', 'voice', 'rare', '{"lang":"es-VE","engine":"google"}'),
('voice_google_fr_BE', 'Google Belgian French', 'Belgian French voice', 'voice', 'rare', '{"lang":"fr-BE","engine":"google"}'),
('voice_google_fr_CH', 'Google Swiss French', 'Swiss French voice', 'voice', 'rare', '{"lang":"fr-CH","engine":"google"}'),
('voice_google_de_AT', 'Google Austrian', 'Austrian German voice', 'voice', 'rare', '{"lang":"de-AT","engine":"google"}'),
('voice_google_de_CH', 'Google Swiss German', 'Swiss German voice', 'voice', 'rare', '{"lang":"de-CH","engine":"google"}'),
('voice_google_it_CH', 'Google Swiss Italian', 'Swiss Italian voice', 'voice', 'rare', '{"lang":"it-CH","engine":"google"}'),

-- Native/System voices for various platforms (Epic)
('voice_native_karen', 'Karen (AU)', 'Australian native voice', 'voice', 'epic', '{"lang":"en-AU","engine":"native","voice":"Karen"}'),
('voice_native_daniel', 'Daniel (UK)', 'British native voice', 'voice', 'epic', '{"lang":"en-GB","engine":"native","voice":"Daniel"}'),
('voice_native_moira', 'Moira (IE)', 'Irish native voice', 'voice', 'epic', '{"lang":"en-IE","engine":"native","voice":"Moira"}'),
('voice_native_samantha', 'Samantha (US)', 'American native voice', 'voice', 'epic', '{"lang":"en-US","engine":"native","voice":"Samantha"}'),
('voice_native_tessa', 'Tessa (ZA)', 'South African native voice', 'voice', 'epic', '{"lang":"en-ZA","engine":"native","voice":"Tessa"}'),
('voice_native_thomas', 'Thomas (FR)', 'French native voice', 'voice', 'epic', '{"lang":"fr-FR","engine":"native","voice":"Thomas"}'),
('voice_native_anna', 'Anna (DE)', 'German native voice', 'voice', 'epic', '{"lang":"de-DE","engine":"native","voice":"Anna"}'),
('voice_native_alice', 'Alice (IT)', 'Italian native voice', 'voice', 'epic', '{"lang":"it-IT","engine":"native","voice":"Alice"}'),
('voice_native_kyoko', 'Kyoko (JP)', 'Japanese native voice', 'voice', 'epic', '{"lang":"ja-JP","engine":"native","voice":"Kyoko"}'),
('voice_native_yuna', 'Yuna (KO)', 'Korean native voice', 'voice', 'epic', '{"lang":"ko-KR","engine":"native","voice":"Yuna"}'),
('voice_native_milena', 'Milena (RU)', 'Russian native voice', 'voice', 'epic', '{"lang":"ru-RU","engine":"native","voice":"Milena"}'),
('voice_native_monica', 'Monica (ES)', 'Spanish native voice', 'voice', 'epic', '{"lang":"es-ES","engine":"native","voice":"Monica"}'),
('voice_native_luciana', 'Luciana (BR)', 'Brazilian native voice', 'voice', 'epic', '{"lang":"pt-BR","engine":"native","voice":"Luciana"}'),
('voice_native_tingting', 'Ting-Ting (CN)', 'Chinese native voice', 'voice', 'epic', '{"lang":"zh-CN","engine":"native","voice":"Ting-Ting"}'),
('voice_native_meijia', 'Mei-Jia (TW)', 'Taiwanese native voice', 'voice', 'epic', '{"lang":"zh-TW","engine":"native","voice":"Mei-Jia"}'),

-- Special character voices (Legendary)
('voice_special_whisper', 'Whisper Voice', 'Mysterious whispering voice', 'voice', 'legendary', '{"lang":"en-US","engine":"special","effect":"whisper"}'),
('voice_special_robot', 'Robot Voice', 'Mechanical robot voice', 'voice', 'legendary', '{"lang":"en-US","engine":"special","effect":"robot"}'),
('voice_special_echo', 'Echo Voice', 'Voice with echo effect', 'voice', 'legendary', '{"lang":"en-US","engine":"special","effect":"echo"}'),
('voice_special_deep', 'Deep Voice', 'Extra deep voice', 'voice', 'legendary', '{"lang":"en-US","engine":"special","effect":"deep"}'),
('voice_special_chipmunk', 'Chipmunk Voice', 'High-pitched chipmunk voice', 'voice', 'legendary', '{"lang":"en-US","engine":"special","effect":"chipmunk"}'),
('voice_special_alien', 'Alien Voice', 'Otherworldly alien voice', 'voice', 'legendary', '{"lang":"en-US","engine":"special","effect":"alien"}'),
('voice_special_ghost', 'Ghost Voice', 'Spooky ghost voice', 'voice', 'legendary', '{"lang":"en-US","engine":"special","effect":"ghost"}'),
('voice_special_pirate', 'Pirate Voice', 'Arr matey pirate voice', 'voice', 'legendary', '{"lang":"en-US","engine":"special","effect":"pirate","accent":"pirate"}'),
('voice_special_cowboy', 'Cowboy Voice', 'Wild west cowboy voice', 'voice', 'legendary', '{"lang":"en-US","engine":"special","effect":"cowboy","accent":"southern"}'),
('voice_special_villain', 'Villain Voice', 'Evil villain voice', 'voice', 'legendary', '{"lang":"en-US","engine":"special","effect":"villain"}'),

-- Additional language variants to reach 209 total
('voice_google_af_ZA_male', 'Google Afrikaans Male', 'Male Afrikaans voice', 'voice', 'uncommon', '{"lang":"af-ZA","engine":"google","gender":"male"}'),
('voice_google_ar_XA_female', 'Google Arabic Female', 'Female Arabic voice', 'voice', 'uncommon', '{"lang":"ar-XA","engine":"google","gender":"female"}'),
('voice_google_bg_BG_male', 'Google Bulgarian Male', 'Male Bulgarian voice', 'voice', 'uncommon', '{"lang":"bg-BG","engine":"google","gender":"male"}'),
('voice_google_bn_IN_female', 'Google Bengali Female', 'Female Bengali voice', 'voice', 'uncommon', '{"lang":"bn-IN","engine":"google","gender":"female"}'),
('voice_google_ca_ES_male', 'Google Catalan Male', 'Male Catalan voice', 'voice', 'uncommon', '{"lang":"ca-ES","engine":"google","gender":"male"}'),
('voice_google_cmn_CN_male', 'Google Mandarin Male', 'Male Mandarin voice', 'voice', 'uncommon', '{"lang":"cmn-CN","engine":"google","gender":"male"}'),
('voice_google_cmn_TW_female', 'Google Taiwan Female', 'Female Taiwanese voice', 'voice', 'uncommon', '{"lang":"cmn-TW","engine":"google","gender":"female"}'),
('voice_google_cs_CZ_male', 'Google Czech Male', 'Male Czech voice', 'voice', 'uncommon', '{"lang":"cs-CZ","engine":"google","gender":"male"}'),
('voice_google_da_DK_female', 'Google Danish Female', 'Female Danish voice', 'voice', 'uncommon', '{"lang":"da-DK","engine":"google","gender":"female"}'),
('voice_google_de_DE_male', 'Google German Male', 'Male German voice', 'voice', 'uncommon', '{"lang":"de-DE","engine":"google","gender":"male"}'),
('voice_google_de_DE_female', 'Google German Female', 'Female German voice', 'voice', 'uncommon', '{"lang":"de-DE","engine":"google","gender":"female"}'),
('voice_google_el_GR_male', 'Google Greek Male', 'Male Greek voice', 'voice', 'uncommon', '{"lang":"el-GR","engine":"google","gender":"male"}'),
('voice_google_en_AU_male', 'Google Australian Male', 'Male Australian voice', 'voice', 'uncommon', '{"lang":"en-AU","engine":"google","gender":"male"}'),
('voice_google_en_AU_female', 'Google Australian Female', 'Female Australian voice', 'voice', 'uncommon', '{"lang":"en-AU","engine":"google","gender":"female"}'),
('voice_google_en_GB_male', 'Google British Male', 'Male British voice', 'voice', 'uncommon', '{"lang":"en-GB","engine":"google","gender":"male"}'),
('voice_google_en_GB_female', 'Google British Female', 'Female British voice', 'voice', 'uncommon', '{"lang":"en-GB","engine":"google","gender":"female"}'),
('voice_google_en_IN_male', 'Google Indian Male', 'Male Indian English voice', 'voice', 'uncommon', '{"lang":"en-IN","engine":"google","gender":"male"}'),
('voice_google_en_IN_female', 'Google Indian Female', 'Female Indian English voice', 'voice', 'uncommon', '{"lang":"en-IN","engine":"google","gender":"female"}'),
('voice_google_en_US_male1', 'Google US Male 1', 'Male American voice 1', 'voice', 'common', '{"lang":"en-US","engine":"google","gender":"male","variant":"1"}'),
('voice_google_en_US_male2', 'Google US Male 2', 'Male American voice 2', 'voice', 'common', '{"lang":"en-US","engine":"google","gender":"male","variant":"2"}'),
('voice_google_en_US_female1', 'Google US Female 1', 'Female American voice 1', 'voice', 'common', '{"lang":"en-US","engine":"google","gender":"female","variant":"1"}'),
('voice_google_en_US_female2', 'Google US Female 2', 'Female American voice 2', 'voice', 'common', '{"lang":"en-US","engine":"google","gender":"female","variant":"2"}'),
('voice_google_es_ES_male', 'Google Spanish Male', 'Male Spanish voice', 'voice', 'uncommon', '{"lang":"es-ES","engine":"google","gender":"male"}'),
('voice_google_es_ES_female', 'Google Spanish Female', 'Female Spanish voice', 'voice', 'uncommon', '{"lang":"es-ES","engine":"google","gender":"female"}'),
('voice_google_es_MX_male', 'Google Mexican Male', 'Male Mexican voice', 'voice', 'uncommon', '{"lang":"es-MX","engine":"google","gender":"male"}'),
('voice_google_es_MX_female', 'Google Mexican Female', 'Female Mexican voice', 'voice', 'uncommon', '{"lang":"es-MX","engine":"google","gender":"female"}'),
('voice_google_fi_FI_male', 'Google Finnish Male', 'Male Finnish voice', 'voice', 'uncommon', '{"lang":"fi-FI","engine":"google","gender":"male"}'),
('voice_google_fil_PH_male', 'Google Filipino Male', 'Male Filipino voice', 'voice', 'uncommon', '{"lang":"fil-PH","engine":"google","gender":"male"}'),
('voice_google_fr_CA_male', 'Google Quebec Male', 'Male Quebec French voice', 'voice', 'uncommon', '{"lang":"fr-CA","engine":"google","gender":"male"}'),
('voice_google_fr_CA_female', 'Google Quebec Female', 'Female Quebec French voice', 'voice', 'uncommon', '{"lang":"fr-CA","engine":"google","gender":"female"}'),
('voice_google_fr_FR_male', 'Google French Male', 'Male French voice', 'voice', 'uncommon', '{"lang":"fr-FR","engine":"google","gender":"male"}'),
('voice_google_fr_FR_female', 'Google French Female', 'Female French voice', 'voice', 'uncommon', '{"lang":"fr-FR","engine":"google","gender":"female"}'),
('voice_google_he_IL_male', 'Google Hebrew Male', 'Male Hebrew voice', 'voice', 'uncommon', '{"lang":"he-IL","engine":"google","gender":"male"}'),
('voice_google_hi_IN_male', 'Google Hindi Male', 'Male Hindi voice', 'voice', 'uncommon', '{"lang":"hi-IN","engine":"google","gender":"male"}'),
('voice_google_hi_IN_female', 'Google Hindi Female', 'Female Hindi voice', 'voice', 'uncommon', '{"lang":"hi-IN","engine":"google","gender":"female"}'),
('voice_google_hu_HU_male', 'Google Hungarian Male', 'Male Hungarian voice', 'voice', 'uncommon', '{"lang":"hu-HU","engine":"google","gender":"male"}'),
('voice_google_id_ID_male', 'Google Indonesian Male', 'Male Indonesian voice', 'voice', 'uncommon', '{"lang":"id-ID","engine":"google","gender":"male"}'),
('voice_google_id_ID_female', 'Google Indonesian Female', 'Female Indonesian voice', 'voice', 'uncommon', '{"lang":"id-ID","engine":"google","gender":"female"}'),
('voice_google_it_IT_male', 'Google Italian Male', 'Male Italian voice', 'voice', 'uncommon', '{"lang":"it-IT","engine":"google","gender":"male"}'),
('voice_google_it_IT_female', 'Google Italian Female', 'Female Italian voice', 'voice', 'uncommon', '{"lang":"it-IT","engine":"google","gender":"female"}'),
('voice_google_ja_JP_male', 'Google Japanese Male', 'Male Japanese voice', 'voice', 'uncommon', '{"lang":"ja-JP","engine":"google","gender":"male"}'),
('voice_google_ja_JP_female', 'Google Japanese Female', 'Female Japanese voice', 'voice', 'uncommon', '{"lang":"ja-JP","engine":"google","gender":"female"}'),
('voice_google_ko_KR_male', 'Google Korean Male', 'Male Korean voice', 'voice', 'uncommon', '{"lang":"ko-KR","engine":"google","gender":"male"}'),
('voice_google_ko_KR_female', 'Google Korean Female', 'Female Korean voice', 'voice', 'uncommon', '{"lang":"ko-KR","engine":"google","gender":"female"}'),
('voice_google_nb_NO_male', 'Google Norwegian Male', 'Male Norwegian voice', 'voice', 'uncommon', '{"lang":"nb-NO","engine":"google","gender":"male"}'),
('voice_google_nb_NO_female', 'Google Norwegian Female', 'Female Norwegian voice', 'voice', 'uncommon', '{"lang":"nb-NO","engine":"google","gender":"female"}'),
('voice_google_nl_NL_male', 'Google Dutch Male', 'Male Dutch voice', 'voice', 'uncommon', '{"lang":"nl-NL","engine":"google","gender":"male"}'),
('voice_google_nl_NL_female', 'Google Dutch Female', 'Female Dutch voice', 'voice', 'uncommon', '{"lang":"nl-NL","engine":"google","gender":"female"}'),
('voice_google_pl_PL_male', 'Google Polish Male', 'Male Polish voice', 'voice', 'uncommon', '{"lang":"pl-PL","engine":"google","gender":"male"}'),
('voice_google_pl_PL_female', 'Google Polish Female', 'Female Polish voice', 'voice', 'uncommon', '{"lang":"pl-PL","engine":"google","gender":"female"}'),
('voice_google_pt_BR_male', 'Google Brazilian Male', 'Male Brazilian voice', 'voice', 'uncommon', '{"lang":"pt-BR","engine":"google","gender":"male"}'),
('voice_google_pt_BR_female', 'Google Brazilian Female', 'Female Brazilian voice', 'voice', 'uncommon', '{"lang":"pt-BR","engine":"google","gender":"female"}'),
('voice_google_pt_PT_male', 'Google Portuguese Male', 'Male Portuguese voice', 'voice', 'uncommon', '{"lang":"pt-PT","engine":"google","gender":"male"}'),
('voice_google_pt_PT_female', 'Google Portuguese Female', 'Female Portuguese voice', 'voice', 'uncommon', '{"lang":"pt-PT","engine":"google","gender":"female"}'),
('voice_google_ru_RU_male', 'Google Russian Male', 'Male Russian voice', 'voice', 'uncommon', '{"lang":"ru-RU","engine":"google","gender":"male"}'),
('voice_google_ru_RU_female', 'Google Russian Female', 'Female Russian voice', 'voice', 'uncommon', '{"lang":"ru-RU","engine":"google","gender":"female"}'),
('voice_google_sv_SE_male', 'Google Swedish Male', 'Male Swedish voice', 'voice', 'uncommon', '{"lang":"sv-SE","engine":"google","gender":"male"}'),
('voice_google_sv_SE_female', 'Google Swedish Female', 'Female Swedish voice', 'voice', 'uncommon', '{"lang":"sv-SE","engine":"google","gender":"female"}'),
('voice_google_th_TH_male', 'Google Thai Male', 'Male Thai voice', 'voice', 'uncommon', '{"lang":"th-TH","engine":"google","gender":"male"}'),
('voice_google_th_TH_female', 'Google Thai Female', 'Female Thai voice', 'voice', 'uncommon', '{"lang":"th-TH","engine":"google","gender":"female"}'),
('voice_google_tr_TR_male', 'Google Turkish Male', 'Male Turkish voice', 'voice', 'uncommon', '{"lang":"tr-TR","engine":"google","gender":"male"}'),
('voice_google_tr_TR_female', 'Google Turkish Female', 'Female Turkish voice', 'voice', 'uncommon', '{"lang":"tr-TR","engine":"google","gender":"female"}'),
('voice_google_uk_UA_male', 'Google Ukrainian Male', 'Male Ukrainian voice', 'voice', 'uncommon', '{"lang":"uk-UA","engine":"google","gender":"male"}'),
('voice_google_uk_UA_female', 'Google Ukrainian Female', 'Female Ukrainian voice', 'voice', 'uncommon', '{"lang":"uk-UA","engine":"google","gender":"female"}'),
('voice_google_vi_VN_male', 'Google Vietnamese Male', 'Male Vietnamese voice', 'voice', 'uncommon', '{"lang":"vi-VN","engine":"google","gender":"male"}'),
('voice_google_vi_VN_female', 'Google Vietnamese Female', 'Female Vietnamese voice', 'voice', 'uncommon', '{"lang":"vi-VN","engine":"google","gender":"female"}'),

-- Additional dialects and accents (Rare/Epic)
('voice_accent_scottish', 'Scottish Accent', 'Scottish accented English', 'voice', 'epic', '{"lang":"en-GB","engine":"google","accent":"scottish"}'),
('voice_accent_welsh', 'Welsh Accent', 'Welsh accented English', 'voice', 'epic', '{"lang":"en-GB","engine":"google","accent":"welsh"}'),
('voice_accent_cockney', 'Cockney Accent', 'Cockney accented English', 'voice', 'epic', '{"lang":"en-GB","engine":"google","accent":"cockney"}'),
('voice_accent_liverpool', 'Liverpool Accent', 'Scouse accented English', 'voice', 'epic', '{"lang":"en-GB","engine":"google","accent":"liverpool"}'),
('voice_accent_yorkshire', 'Yorkshire Accent', 'Yorkshire accented English', 'voice', 'epic', '{"lang":"en-GB","engine":"google","accent":"yorkshire"}'),
('voice_accent_texas', 'Texas Accent', 'Texan accented English', 'voice', 'epic', '{"lang":"en-US","engine":"google","accent":"texas"}'),
('voice_accent_boston', 'Boston Accent', 'Boston accented English', 'voice', 'epic', '{"lang":"en-US","engine":"google","accent":"boston"}'),
('voice_accent_newyork', 'New York Accent', 'New York accented English', 'voice', 'epic', '{"lang":"en-US","engine":"google","accent":"newyork"}'),
('voice_accent_southern', 'Southern Accent', 'Southern US accented English', 'voice', 'epic', '{"lang":"en-US","engine":"google","accent":"southern"}'),
('voice_accent_valley', 'Valley Girl', 'Valley girl accented English', 'voice', 'legendary', '{"lang":"en-US","engine":"google","accent":"valley"}'),

-- Child voices (Epic)
('voice_child_boy_us', 'American Boy', 'Young American boy voice', 'voice', 'epic', '{"lang":"en-US","engine":"google","age":"child","gender":"male"}'),
('voice_child_girl_us', 'American Girl', 'Young American girl voice', 'voice', 'epic', '{"lang":"en-US","engine":"google","age":"child","gender":"female"}'),
('voice_child_boy_uk', 'British Boy', 'Young British boy voice', 'voice', 'epic', '{"lang":"en-GB","engine":"google","age":"child","gender":"male"}'),
('voice_child_girl_uk', 'British Girl', 'Young British girl voice', 'voice', 'epic', '{"lang":"en-GB","engine":"google","age":"child","gender":"female"}'),

-- Senior voices (Rare)
('voice_senior_man_us', 'American Grandpa', 'Elderly American man voice', 'voice', 'rare', '{"lang":"en-US","engine":"google","age":"senior","gender":"male"}'),
('voice_senior_woman_us', 'American Grandma', 'Elderly American woman voice', 'voice', 'rare', '{"lang":"en-US","engine":"google","age":"senior","gender":"female"}'),
('voice_senior_man_uk', 'British Grandpa', 'Elderly British man voice', 'voice', 'rare', '{"lang":"en-GB","engine":"google","age":"senior","gender":"male"}'),
('voice_senior_woman_uk', 'British Grandma', 'Elderly British woman voice', 'voice', 'rare', '{"lang":"en-GB","engine":"google","age":"senior","gender":"female"}'),

-- Professional voices (Rare)
('voice_news_anchor_us', 'US News Anchor', 'American news anchor voice', 'voice', 'rare', '{"lang":"en-US","engine":"google","style":"news"}'),
('voice_news_anchor_uk', 'BBC News', 'British news presenter voice', 'voice', 'rare', '{"lang":"en-GB","engine":"google","style":"news"}'),
('voice_narrator_documentary', 'Documentary', 'Documentary narrator voice', 'voice', 'rare', '{"lang":"en-US","engine":"google","style":"documentary"}'),
('voice_narrator_audiobook', 'Audiobook', 'Audiobook narrator voice', 'voice', 'rare', '{"lang":"en-US","engine":"google","style":"audiobook"}'),
('voice_assistant_professional', 'Professional', 'Professional assistant voice', 'voice', 'rare', '{"lang":"en-US","engine":"google","style":"professional"}'),
('voice_assistant_friendly', 'Friendly', 'Friendly assistant voice', 'voice', 'rare', '{"lang":"en-US","engine":"google","style":"friendly"}'),

-- Singing voices (Legendary)
('voice_singing_soprano', 'Soprano Singer', 'Soprano singing voice', 'voice', 'legendary', '{"lang":"en-US","engine":"special","type":"singing","range":"soprano"}'),
('voice_singing_alto', 'Alto Singer', 'Alto singing voice', 'voice', 'legendary', '{"lang":"en-US","engine":"special","type":"singing","range":"alto"}'),
('voice_singing_tenor', 'Tenor Singer', 'Tenor singing voice', 'voice', 'legendary', '{"lang":"en-US","engine":"special","type":"singing","range":"tenor"}'),
('voice_singing_bass', 'Bass Singer', 'Bass singing voice', 'voice', 'legendary', '{"lang":"en-US","engine":"special","type":"singing","range":"bass"}'),

-- Celebrity impressions (Legendary)
('voice_celeb_morgan', 'Morgan Voice', 'Deep narrative voice', 'voice', 'legendary', '{"lang":"en-US","engine":"special","style":"morgan"}'),
('voice_celeb_british_sir', 'British Sir', 'Distinguished British voice', 'voice', 'legendary', '{"lang":"en-GB","engine":"special","style":"distinguished"}'),
('voice_celeb_movie_trailer', 'Movie Trailer', 'Epic movie trailer voice', 'voice', 'legendary', '{"lang":"en-US","engine":"special","style":"trailer"}'),
('voice_celeb_game_announcer', 'Game Announcer', 'Video game announcer voice', 'voice', 'legendary', '{"lang":"en-US","engine":"special","style":"game_announcer"}'),

-- Fantasy/Gaming voices (Legendary)
('voice_fantasy_wizard', 'Wizard Voice', 'Mystical wizard voice', 'voice', 'legendary', '{"lang":"en-US","engine":"special","character":"wizard"}'),
('voice_fantasy_elf', 'Elf Voice', 'Ethereal elf voice', 'voice', 'legendary', '{"lang":"en-US","engine":"special","character":"elf"}'),
('voice_fantasy_dwarf', 'Dwarf Voice', 'Gruff dwarf voice', 'voice', 'legendary', '{"lang":"en-US","engine":"special","character":"dwarf"}'),
('voice_fantasy_orc', 'Orc Voice', 'Brutal orc voice', 'voice', 'legendary', '{"lang":"en-US","engine":"special","character":"orc"}'),
('voice_fantasy_dragon', 'Dragon Voice', 'Mighty dragon voice', 'voice', 'legendary', '{"lang":"en-US","engine":"special","character":"dragon"}');

-- Verify total count
SELECT COUNT(*) as total_voices FROM reward_types WHERE category = 'voice';